Repository Pive-Guyz/be14-fin-Empick-BE, pull requests merged in 2025-06, with the labels that each got.

#9 [refactor] 면접 도메인 패키지 구조 생성
  src/main/java/com/piveguyz/empickbackend/interview/command/application/controller/InterviewCommandController.java
  src/main/java/com/piveguyz/empickbackend/interview/command/application/dto/InterviewCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/interview/command/application/service/InterviewCommandService.java
  src/main/java/com/piveguyz/empickbackend/interview/command/application/service/InterviewCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interview/command/domain/aggregate/InterviewEntity.java
  src/main/java/com/piveguyz/empickbackend/interview/command/domain/repository/InterviewRepository.java
  src/main/java/com/piveguyz/empickbackend/interview/query/controller/InterviewQueryController.java
  src/main/java/com/piveguyz/empickbackend/interview/query/dto/InterviewQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/interview/query/mapper/InterviewMapper.java
  src/main/java/com/piveguyz/empickbackend/interview/query/service/InterviewQueryService.java
  src/main/java/com/piveguyz/empickbackend/interview/query/service/InterviewQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/command/application/controller/InterviewCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/command/application/dto/InterviewCriteriaCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/command/application/service/InterviewCriteriaCommandService.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/command/application/service/InterviewCriteriaCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/command/domain/aggregate/InterviewCriteriaEntity.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/command/domain/repository/InterviewCriteriaRepository.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/query/controller/InterviewCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/query/dto/InterviewCriteriaQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/query/mapper/InterviewCriteriaMapper.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/query/service/InterviewCriteriaQueryService.java
  src/main/java/com/piveguyz/empickbackend/interviewCriteria/query/service/InterviewCriteriaQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/command/application/controller/InterviewScoreCommandController.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/command/application/dto/InterviewScoreCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/command/application/service/InterviewScoreCommandService.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/command/application/service/InterviewScoreCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/command/domain/aggregate/InterviewScoreEntity.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/command/domain/repository/InterviewScoreRepository.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/query/controller/InterviewScoreQueryController.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/query/dto/InterviewScoreQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/query/mapper/InterviewScoreMapper.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/query/service/InterviewScoreQueryService.java
  src/main/java/com/piveguyz/empickbackend/interviewScore/query/service/InterviewScoreQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/command/application/controller/InterviewSheetCommandController.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/command/application/dto/InterviewSheetCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/command/application/service/InterviewSheetCommandService.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/command/application/service/InterviewSheetCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/command/domain/aggregate/InterviewSheetEntity.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/command/domain/repository/InterviewSheetRepository.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/query/controller/InterviewSheetQueryController.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/query/dto/InterviewSheetQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/query/mapper/InterviewSheetMapper.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/query/service/InterviewSheetQueryService.java
  src/main/java/com/piveguyz/empickbackend/interviewSheet/query/service/InterviewSheetQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/command/application/controller/InterviewSheetItemCommandController.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/command/application/dto/InterviewSheetItemCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/command/application/service/InterviewSheetItemCommandService.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/command/application/service/InterviewSheetItemCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/command/domain/aggregate/InterviewSheetItemEntity.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/command/domain/repository/InterviewSheetItemRepository.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/query/controller/InterviewSheetItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/query/dto/InterviewSheetItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/query/mapper/InterviewSheetItemMapper.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/query/service/InterviewSheetItemQueryService.java
  src/main/java/com/piveguyz/empickbackend/interviewSheetItem/query/service/InterviewSheetItemQueryServiceImpl.java
  src/main/resources/java/com/piveguyz/empickbackend/interview/query/mapper/interviewMapper.xml
Labels: 🔧 refactoring

#6 [feat] 실무 테스트 관련 테이블 생성
  src/main/resources/schema/tables/job_test.sql
Labels: :sparkles: enhancement

#24 [chore] api 응답 공통 클래스 생성
  src/main/java/com/piveguyz/empickbackend/common/response/ApiResponse.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
Labels: :sparkles: enhancement, 🚨 HOTFIX

#28 [chore] 실무테스트 패키지 구조 생성 1차
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/controller/JobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/controller/JobtestQuestionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/controller/JobtestTypeCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/dto/JobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/dto/JobtestQuestionCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/dto/JobtestTypeCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/JobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/JobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/JobtestQuestionCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/JobtestQuestionCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/JobtestTypeCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/JobtestTypeCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/domain/aggregate/JobtestEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/domain/aggregate/JobtestQuestionEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/domain/aggregate/JobtestTypeEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/domain/repository/JobtestQuestionRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/domain/repository/JobtestRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/domain/repository/JobtestTypeRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/controller/JobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/controller/JobtestQuestionQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/controller/JobtestTypeQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/dto/JobtestQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/dto/JobtestQuestionQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/dto/JobtestTypeQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/mapper/JobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/mapper/JobtestQuestionMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/mapper/JobtestTypeMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/service/JobtestQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/service/JobtestQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/service/JobtestQuestionQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/service/JobtestQuestionQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/service/JobtestTypeQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/query/service/JobtestTypeQueryServiceImpl.java
Labels: :sparkles: enhancement

#26 [feat] JWT 2, 3단계 개발
  src/main/java/com/piveguyz/empickbackend/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/dto/LoginRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/dto/LoginResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/service/AuthCommandService.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/auth/command/jwt/JwtAuthenticationFilter.java
  src/main/java/com/piveguyz/empickbackend/auth/command/jwt/JwtProvider.java
  src/main/java/com/piveguyz/empickbackend/common/config/OpenApiConfig.java
  src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
  src/main/java/com/piveguyz/empickbackend/common/util/JwtSecretGenerator.java
  src/main/java/com/piveguyz/empickbackend/common/util/PasswordEncoder.java
  src/main/java/com/piveguyz/empickbackend/member/command/domain/aggregate/Member.java
  src/main/java/com/piveguyz/empickbackend/member/query/controller/MemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/member/query/dto/MemberResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/member/query/service/MemberQueryService.java
  src/main/java/com/piveguyz/empickbackend/member/query/service/MemberQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/security/CustomMemberDetailsService.java
Labels: :sparkles: enhancement

#20 [feat] 지원자관련 테이블 추가
  src/main/resources/application.yml
  src/main/resources/schema/tables/application.sql
  src/main/resources/schema/tables/introduce.sql
Labels: :sparkles: enhancement

#35 [chore] 채용공고 및 지원서 양식 패키지 구조 생성
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/application/controller/ApplicationItemCommandController.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/application/dto/ApplicationItemCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/application/service/ApplicationItemCommandService.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/application/service/ApplicationItemCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/domain/aggregate/ApplicationItem.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/domain/aggregate/ApplicationItemCategory.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/domain/repository/ApplicationItemCategoryRepository.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/command/domain/repository/ApplicationItemRepository.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/query/controller/ApplicationItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/query/dto/ApplicationItemCategoryDTO.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/query/dto/ApplicationItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/query/mapper/ApplicationItemQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/query/service/ApplicationItemQueryService.java
  src/main/java/com/piveguyz/empickbackend/applicationItem/query/service/ApplicationItemQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/recruitment/command/application/controller/RecruitmentCommandController.java
  src/main/java/com/piveguyz/empickbackend/recruitment/command/application/dto/RecruitmentCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/recruitment/command/application/service/RecruitmentCommandService.java
  src/main/java/com/piveguyz/empickbackend/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/recruitment/command/domain/aggregate/Recruitment.java
  src/main/java/com/piveguyz/empickbackend/recruitment/command/domain/repository/RecruitmentRepository.java
  src/main/java/com/piveguyz/empickbackend/recruitment/query/controller/RecruitmentQueryController.java
  src/main/java/com/piveguyz/empickbackend/recruitment/query/dto/RecruitmentQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/recruitment/query/mapper/RecruitmentQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/recruitment/query/service/RecruitmentQueryService.java
  src/main/java/com/piveguyz/empickbackend/recruitment/query/service/RecruitmentQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/application/controller/RecruitmentTemplateCommandController.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/application/dto/RecruitmentTemplateCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/application/service/RecruitmentTemplateCommandService.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/application/service/RecruitmentTemplateCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/domain/aggregate/RecruitmentTemplate.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/domain/aggregate/RecruitmentTemplateItem.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/domain/repository/RecruitmentTemplateItemRepository.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/command/domain/repository/RecruitmentTemplateRepository.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/query/controller/RecruitmentTemplateQueryController.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/query/dto/RecruitmentTemplateQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/query/mapper/RecruitmentTemplateQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/query/service/RecruitmentTemplateQueryService.java
  src/main/java/com/piveguyz/empickbackend/recruitmentTemplate/query/service/RecruitmentTemplateQueryServiceImpl.java
Labels: :sparkles: enhancement

#53 [feat] custom api response HttpStatus도 함께 저장
  src/main/java/com/piveguyz/empickbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/controller/QuestionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtest/command/application/service/QuestionCommandServiceImpl.java
Labels: 🔧 refactoring, 🚨 HOTFIX

#54 [refactor] 인증 API : JWT 권한 추가
  build.gradle
  src/main/java/com/piveguyz/empickbackend/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/dto/LoginRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/auth/command/jwt/JwtProvider.java
  src/main/java/com/piveguyz/empickbackend/common/constants/ApiExamples.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/member/query/controller/MemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/member/query/mapper/MemberMapper.java
  src/main/java/com/piveguyz/empickbackend/security/CustomMemberDetailsService.java
  src/main/resources/java/com/piveguyz/empickbackend/member/query/mapper/MemberMapper.xml
  src/main/resources/schema/seed/member_insert.sql
  src/main/resources/schema/seed/role_insert.sql
  src/main/resources/schema/tables/common.sql
  src/main/resources/schema/tables/member.sql
  src/main/resources/schema/tables/role.sql
  src/test/java/com/piveguyz/empickbackend/security/CustomMemberDetailsServiceTest.java
Labels: :sparkles: enhancement

#56 [refactor] 채용공고 테이블 수정
  src/main/resources/schema/tables/recruitment.sql
Labels: 🔧 refactoring

#81 [hotfix] mapper 패키지 경로 변경 / 중복 클래스명 수정
  src/main/java/com/piveguyz/empickbackend/Application.java
  src/main/java/com/piveguyz/empickbackend/common/config/MapperConfig.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/ApplicationForm.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/domain/repository/InterviewRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/command/domain/repository/InterviewCriteriaRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/command/domain/repository/InterviewScoreRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/command/domain/repository/InterviewSheetRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheetItem/command/domain/repository/InterviewSheetItemRepository.java
  src/main/resources/mapper/interview/interviewMapper.xml
  src/main/resources/mapper/mail/MailMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
Labels: 🚨 HOTFIX

#60 [feat] 안내 메일 / 안내 메일 템플릿 백엔드 구현
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/controller/MailQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/mapper/MailMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/service/MailQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/mailTemplate/command/application/service/MailTemplateCommandServiceImpl.java
  src/main/resources/mapper/mailTemplate/mailTemplateMapper.xml
Labels: :sparkles: enhancement

#67 [feat] 면접 평가 기준 Query 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/query/controller/InterviewCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/query/mapper/InterviewCriteriaMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/query/service/InterviewCriteriaQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/query/service/InterviewCriteriaQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/controller/MailQueryController.java
  src/main/resources/mapper/interviewCriteria/InterviewCriteriaMapper.xml
Labels: :sparkles: enhancement

#82 [feat] 면접 평가 기준 Command 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/command/application/controller/InterviewCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/command/application/mapper/InterviewCriteriaCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/command/application/service/InterviewCriteriaCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/command/application/service/InterviewCriteriaCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewCriteria/command/domain/repository/InterviewCriteriaRepository.java
Labels: :sparkles: enhancement

#84 [feat] 면접 평가표 Query / Command 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/command/application/controller/InterviewSheetCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/command/application/mapper/InterviewSheetCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/command/application/service/InterviewSheetCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/command/application/service/InterviewSheetCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/command/domain/repository/InterviewSheetRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/query/controller/InterviewSheetQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/query/mapper/InterviewSheetMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/query/service/InterviewSheetQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewSheet/query/service/InterviewSheetQueryServiceImpl.java
  src/main/resources/mapper/interview_sheet/InterviewSheetMapper.xml
Labels: :sparkles: enhancement

#101 [refactor] 순환 참조되던 컬럼 삭제
  src/main/resources/schema/tables/applicant.sql
Labels: :bug: bug, 🚨 HOTFIX

#102 [refactor] SQL drop 구문 추가
  src/main/resources/schema/tables/interview.sql
  src/main/resources/schema/tables/mail.sql
Labels: 🔧 refactoring

#106 [hotfix] jobtestType 중복 파일 삭제
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/command/application/controller/JobtestTypeCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/command/application/dto/JobtestTypeCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/command/application/service/JobtestTypeCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/command/application/service/JobtestTypeCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/command/domain/aggregate/JobtestTypeEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/command/domain/repository/JobtestTypeRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/query/controller/JobtestTypeQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/query/dto/JobtestTypeQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/query/mapper/JobtestTypeMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/query/service/JobtestTypeQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtestType/query/service/JobtestTypeQueryServiceImpl.java
Labels: :bug: bug, 🚨 HOTFIX

#103 [feat] 부서, 직무 등 더미 데이터 일부 추가(사원 만들기용)
  src/main/resources/schema/seed/role_insert.sql
Labels: :sparkles: enhancement

#113 [feat] 채용공고 등록, 수정, 삭제, 조회 기능 / 지원서 항목 카테고리 조회 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/handler/InputTypeHandler.java
  src/main/java/com/piveguyz/empickbackend/common/handler/RecruitTypeHandler.java
  src/main/java/com/piveguyz/empickbackend/common/handler/RecruitmentStatusHandler.java
  src/main/java/com/piveguyz/empickbackend/common/handler/YnBooleanTypeHandler.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/application/dto/ApplicationItemCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/aggregate/ApplicationItem.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/aggregate/ApplicationItemCategory.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/repository/ApplicationItemCategoryRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/repository/ApplicationItemRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/ApplicationItemCategoryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/ApplicationItemCategoryQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/ApplicationItemCreateDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/ApplicationItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/InputType.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/mapper/ApplicationItemCategoryQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/mapper/ApplicationItemQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/service/ApplicationItemCategoryQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/service/ApplicationItemCategoryQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/service/ApplicationItemQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/service/ApplicationItemQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/dto/RecruitmentCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/aggregate/Recruitment.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/converter/RecruitTypeConverter.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/converter/RecruitmentStatusConverter.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/enums/RecruitType.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/enums/RecruitmentStatus.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/repository/RecruitmentRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/controller/RecruitmentQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/dto/RecruitmentQueryConditionDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/dto/RecruitmentQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/mapper/RecruitmentQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/service/RecruitmentQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/service/RecruitmentQueryServiceImpl.java
  src/main/resources/mapper/applicationItem/ApplicationItemQueryMapper.xml
  src/main/resources/mapper/recruitment/RecruitmentQueryMapper.xml
Labels: :sparkles: enhancement

#96 [feat] 지원자 북마크 전체 조회 개발
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicantBookmarkCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantBookmarkQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantBookmarkQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicantBookmarkMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicantMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantBookmarkQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantBookmarkQueryServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryServiceImp.java
  src/main/resources/mapper/applicant/applicantBookmarkMapper.xml
  src/main/resources/mapper/applicant/applicantMapper.xml
Labels: :sparkles: enhancement

#120 [feat] 면접 Command / Query 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/application/controller/InterviewCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/application/dto/InterviewCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/application/mapper/InterviewCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/application/service/InterviewCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/application/service/InterviewCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/domain/aggregate/InterviewEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/query/controller/InterviewQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/query/dto/InterviewQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/query/mapper/InterviewMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/query/service/InterviewQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/interview/query/service/InterviewQueryServiceImpl.java
  src/main/resources/mapper/interview/interviewMapper.xml
  src/main/resources/schema/seed/interview_insert.sql
Labels: :sparkles: enhancement

#124 [feat] 면접 평가 점수 Query 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/query/controller/InterviewScoreQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/query/mapper/InterviewScoreMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/query/service/InterviewScoreQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/query/service/InterviewScoreQueryServiceImpl.java
  src/main/resources/mapper/interview_score.InterviewScoreMapper.xml
  src/main/resources/schema/seed/interview_score_insert.sql
Labels: :sparkles: enhancement

#121 [feat] 사원 등록 API 구현
  src/main/java/com/piveguyz/empickbackend/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/piveguyz/empickbackend/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/auth/command/jwt/JwtAuthenticationFilter.java
  src/main/java/com/piveguyz/empickbackend/common/constants/ApiExamples.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/controller/MemberCommandController.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/dto/MemberSignUpRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/dto/MemberSignUpResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandService.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/member/command/domain/aggregate/Member.java
  src/main/java/com/piveguyz/empickbackend/member/command/domain/repository/MemberRepository.java
  src/main/java/com/piveguyz/empickbackend/member/query/controller/MemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/security/CustomMemberDetails.java
  src/main/resources/schema/tables/member.sql
  src/test/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandServiceImplTest.java
Labels: :sparkles: enhancement

#134 [feat] db 예외 상황 추가
  src/main/java/com/piveguyz/empickbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
Labels: :sparkles: enhancement

#79 [feat] 자기소개서 패키지 생성 및 조회 개발
  src/main/java/com/piveguyz/empickbackend/employment/interview/command/application/dto/InterviewCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceQueryController.java
  src/main/resources/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceMapper.xml
Labels: :sparkles: enhancement

#136 [feat] 사원 프로필 업로드/다운로드 (퍼사드 패턴 적용)
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/infra/s3/service/S3Service.java
  src/main/java/com/piveguyz/empickbackend/infra/s3/service/S3ServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/controller/MemberCommandController.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/dto/MemberProfileUploadRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/facade/MemberProfileCommandFacade.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandService.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/member/command/domain/aggregate/Member.java
  src/main/java/com/piveguyz/empickbackend/member/query/controller/MemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/member/query/facade/MemberProfileQueryFacade.java
  src/main/java/com/piveguyz/empickbackend/member/query/service/MemberQueryService.java
  src/main/java/com/piveguyz/empickbackend/member/query/service/MemberQueryServiceImpl.java
Labels: :sparkles: enhancement, 🔧 refactoring

#144 [feat] 지원서 수정 및 조회 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/aggregate/ApplicationItem.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/repository/ApplicationItemRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/ApplicationItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/mapper/ApplicationItemQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/service/ApplicationItemQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/service/ApplicationItemQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/aggregate/Recruitment.java
  src/main/resources/mapper/applicationItem/ApplicationItemCategoryMapper.xml
  src/main/resources/mapper/applicationItem/ApplicationItemMapper.xml
Labels: :sparkles: enhancement

#151 [feat] 실무테스트 문제 채점 기준 & 결과 등록, 수정, 삭제, 조회 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/GradingResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/dto/CreateGradingResultCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/dto/GradingResultCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/dto/UpdateGradingResultCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/mapper/GradingResultMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/service/GradingResultCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/service/GradingResultCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/domain/aggregate/GradingResultEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/domain/repository/GradingResultRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/query/mapper/GradingResultMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/controller/GradingCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/dto/CreateGradingCriteriaCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/dto/GradingCriteriaCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/dto/UpdateGradingCriteriaCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/mapper/GradingCriteriaMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/service/GradingCriteriaCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/service/GradingCriteriaCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/domain/aggregate/GradingCriteriaEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/domain/repository/GradingCriteriaRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/query/controller/GradingCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/query/dto/GradingCriteriaQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/query/mapper/GradingCriteriaMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/query/service/GradingCriteriaQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/query/service/GradingCriteriaQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionOptionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/dto/QuestionQueryDTO.java
  src/main/resources/mapper/jobtest/QuestionMapper.xml
Labels: :sparkles: enhancement

#157 [feat] 면접 평가 점수 Command 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/command/application/controller/InterviewScoreCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/command/application/mapper/InterviewScoreCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/command/application/service/InterviewScoreCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/command/application/service/InterviewScoreCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviewScore/command/domain/repository/InterviewScoreRepository.java
Labels: :sparkles: enhancement

#152 [feat] 채용공고별 프로세스 등록/수정/조회 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/handler/StepTypeHandler.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/dto/RecruitmentCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/application/dto/RecruitmentProcessCreateDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/domain/aggregate/RecruitmentProcess.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/domain/enums/StepType.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/domain/repository/RecruitmentProcessRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/controller/RecruitmentProcessQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/dto/RecruitmentProcessQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/mapper/RecruitmentProcessQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/service/RecruitmentProcessQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/service/RecruitmentProcessQueryServiceImpl.java
  src/main/resources/mapper/recruitment/RecruitmentProcessMapper.xml
Labels: :sparkles: enhancement

#170 [feat] 자기소개서 기준표 전체 조회
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
  src/main/resources/mapper/introduce/IntroduceStandardMapper.xml
Labels: :sparkles: enhancement

#161 [feat] 이메일 발송 기능 구현
  build.gradle
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/config/MailConfig.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/config/ThymeleafConfig.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/dto/MailCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/mapper/MailCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/domain/aggregate/MailEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/dto/MailQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/service/MailQueryServiceImpl.java
  src/main/resources/mapper/interview_score/InterviewScoreMapper.xml
  src/main/resources/mapper/mail/MailMapper.xml
  src/main/resources/schema/tables/mail.sql
  src/main/resources/static/images/banner.png
  src/main/resources/static/images/empick-logo.png
  src/main/resources/templates/email-template.html
Labels: :sparkles: enhancement

#176 [feat] 채용공고 템플릿 복사본 생성 및 조회 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/handler/YnBooleanConverter.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/application/service/RecruitmentTemplateCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/domain/aggregate/RecruitmentTemplate.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/domain/repository/RecruitmentTemplateItemRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/query/dto/RecruitmentTemplateQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/command/application/service/RecruitmentTemplateCopyCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/command/application/service/RecruitmentTemplateCopyTemplateCopyCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/command/domain/aggregate/RecruitmentTemplateCopy.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/command/domain/repository/RecruitmentTemplateCopyRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/controller/RecruitmentTemplateCopyQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/dto/RecruitmentTemplateCopyQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/mapper/RecruitmentTemplateCopyQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/service/RecruitmentTemplateCopyQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/service/RecruitmentTemplateCopyQueryServiceImpl.java
  src/main/resources/mapper/recruitment/RecruitmentTemplateCopyQueryMapper.xml
  src/main/resources/mapper/recruitment/RecruitmentTemplateQueryMapper.xml
  src/main/resources/schema/tables/recruitment.sql
Labels: :sparkles: enhancement

#99 [feat] 자소서 평가 결과표 전체 조회 개발
  src/main/java/com/piveguyz/empickbackend/common/handler/IntroduceResultStatusHandler.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceResultStatus.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceResultQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceResultQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceResultMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceQueryServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceResultQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceResultQueryServiceImp.java
  src/main/resources/mapper/introduce/introduceMapper.xml
  src/main/resources/mapper/introduce/introduceResultMapper.xml
Labels: :sparkles: enhancement

#159 [feat] 자기소개서 항목별 내용 조회 개발
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationResponseQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicationQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicationResponseQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicationResponseQueryDTO.kt
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicationResponseMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationResponseQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationResponseQueryServiceImp.java
  src/main/resources/mapper/applicant/applicationResponseMapper.xml
Labels: :sparkles: enhancement

#163 [feat] 자기소개서 템플릿 항목 조회
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicationResponseQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceTemplateQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceTemplateItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceTemplateQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceTemplateMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateQueryServiceImp.java
  src/main/resources/mapper/introduce/IntroduceTemplateMapper.xml
  src/main/resources/mapper/introduce/IntroduceTemplateMapperItem.xml
Labels: :sparkles: enhancement

#203 [refactor] applicaion_job_test sql문 수정
  src/main/resources/schema/tables/job_test.sql
Labels: 🔧 refactoring, 🚨 HOTFIX

#199 [feat] 사원 정보(퇴사, 부서이동내역) 관리및 조회 API
  src/main/java/com/piveguyz/empickbackend/auth/facade/AuthFacade.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/department/command/application/controller/DeptChangeHistoryCommandController.java
  src/main/java/com/piveguyz/empickbackend/department/command/application/service/DeptChangeHistoryCommandService.java
  src/main/java/com/piveguyz/empickbackend/department/command/application/service/DeptChangeHistoryCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/department/command/domain/aggregate/DeptChangeHistoryEntity.java
  src/main/java/com/piveguyz/empickbackend/department/command/domain/repository/DeptChangeHistoryRepository.java
  src/main/java/com/piveguyz/empickbackend/department/command/domain/repository/DeptRepository.java
  src/main/java/com/piveguyz/empickbackend/department/query/controller/DeptChangeHistoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/department/query/dto/DeptChangeHistoryQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/department/query/mapper/DeptChangeHistoryMapper.java
  src/main/java/com/piveguyz/empickbackend/department/query/service/DeptChangeHistoryQueryService.java
  src/main/java/com/piveguyz/empickbackend/department/query/service/DeptChangeHistoryQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/controller/MemberCommandController.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandService.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/member/command/application/service/MemberEditProposalCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/member/command/domain/aggregate/MemberEntity.java
  src/main/resources/mapper/department/DeptChangeHistoryMapper.xml
Labels: :sparkles: enhancement, 🔧 refactoring

#204 [refactor] 채용공고 관련 도메인 API 엔드포인트/필드타입/채용공고 생성 기능 수정
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/application/controller/ApplicationItemCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/application/dto/ApplicationItemCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/application/service/ApplicationItemCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/application/service/ApplicationItemCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/command/domain/aggregate/ApplicationItem.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/dto/ApplicationItemCreateDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/application/controller/RecruitmentTemplateCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/domain/aggregate/RecruitmentTemplate.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/domain/repository/RecruitmentTemplateRepository.java
Labels: :sparkles: enhancement

#211 [feat] 지원서별 실무테스트 등록/수정/삭제/조회 구현
  src/main/java/com/piveguyz/empickbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/piveguyz/empickbackend/common/handler/JobtestStatusHandler.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/CreateApplicationJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateApplicationJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/mapper/ApplicationJobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/aggregate/ApplicationJobtestEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/aggregate/enums/JobtestStatus.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/ApplicationJobtestRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/ApplicationJobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/JobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/ApplicationInfoDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/ApplicationJobtestQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestApplicationsDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/mapper/ApplicationJobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/ApplicationJobtestQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/ApplicationJobtestQueryServiceImpl.java
  src/main/resources/mapper/jobtest/ApplicationJobtestMapper.xml
  src/main/resources/mapper/jobtest/JobtestMapper.xml
  src/main/resources/schema/tables/job_test.sql
Labels: :sparkles: enhancement

#215 [refactor] 실무테스트 시작, 종료 일시 추가
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/CreateJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/mapper/JobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/aggregate/JobtestEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestApplicationsDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestQueryDTO.java
  src/main/resources/mapper/jobtest/JobtestMapper.xml
Labels: 🔧 refactoring

#220 [refactor] api 경로 수정, swagger tag 형식 통일
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/AnswerCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/GradingResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationResultQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/controller/GradingCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestQuestionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/ApplicationJobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/JobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionOptionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/controller/QuestionQueryController.java
Labels: 🔧 refactoring

#218 [style] : 사원, 부서, S3 API doc 수정
  src/main/java/com/piveguyz/empickbackend/calculator/query/controller/CalculatorQueryController.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/counter/query/controller/CounterQueryController.java
  src/main/java/com/piveguyz/empickbackend/infra/s3/controller/S3Controller.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/application/controller/DeptChangeHistoryCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/controller/DeptChangeHistoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/controller/DeptMemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberEditProposalCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/dto/ProposalStatusUpdateDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/service/MemberEditProposalCommandService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/service/MemberEditProposalCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
Labels: :womans_clothes: style, 🔧 refactoring

#222 [refactor] 채용공고 관련 도메인 api 경로, swagger tag 형식 수정
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicationItem/query/controller/ApplicationItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/controller/RecruitmentQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/query/controller/RecruitmentProcessQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/controller/RecruitmentRequestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/query/controller/RecruitmentRequestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/command/application/controller/RecruitmentTemplateCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplate/query/controller/RecruitmentTemplateQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/query/controller/RecruitmentTemplateCopyQueryController.java
Labels: 🔧 refactoring

#227 [feat] 지원서 항목별 내용 등록
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicationResponseCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/dto/ApplicationResponseCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/mapper/ApplicationResponseCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationResponseCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationResponseCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/ApplicationResponseEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/repository/ApplicationResponseRepository.java
Labels: :sparkles: enhancement

#224 [refactor] 채용공고 템플릿 복사본 Service 파일명 변경
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentTemplateCopy/command/application/service/RecruitmentTemplateCopyCommandServiceImpl.java
Labels: 🔧 refactoring

#229 [feat] 실무테스트 답안 제출 시 자동 채점 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/AnswerCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/dto/CreateAnswerCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/dto/CreateAnswerResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/dto/UpdateAnswerCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/mapper/AnswerMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/service/AnswerCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/service/AnswerCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/domain/aggregate/AnswerEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/domain/repository/AnswerRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/domain/repository/GradingResultRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/dto/CreateEvaluationResultCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/dto/UpdateEvaluationResultCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/domain/aggregate/EvaluationResultEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationResultQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/dto/EvaluationResultQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/dto/JobTestEvaluationDetailDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/mapper/EvaluationResultMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/service/EvaluationResultQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/service/EvaluationResultQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/service/GradingCriteriaCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/domain/aggregate/GradingCriteriaEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/domain/repository/GradingCriteriaRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/CreateApplicationJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateApplicationJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestQuestionCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/aggregate/ApplicationJobtestEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/JobtestQuestionRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/ApplicationJobtestQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/service/QuestionQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/facade/JobtestFacade.java
  src/main/resources/schema/tables/job_test.sql
Labels: :sparkles: enhancement, 🔧 refactoring

#231 [feat] 지원서 command 기능 개발
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/controller/ApplicationCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/dto/ApplicationCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/mapper/ApplicantBookmarkCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/mapper/ApplicationCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicantBookmarkCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/ApplicationEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/applicationBookmark/ApplicantBookmarkEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/applicationBookmark/ApplicantBookmarkId.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/repository/ApplicantBookmarkRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/repository/ApplicationRepository.java
  src/main/resources/mapper/applicant/applicationMapper.xml
Labels: :sparkles: enhancement

#236 [refactor] 채용 요청서 테이블에 직무 컬럼 추가
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/dto/RecruitmentRequestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/service/RecruitmentRequestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/domain/aggregate/RecruitmentRequest.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/query/dto/RecruitmentRequestQueryDTO.java
  src/main/resources/mapper/recruitmentRequest/query/mapper/RecruitmentRequestQueryMapper.xml
  src/main/resources/schema/tables/recruitment.sql
Labels: 🔧 refactoring

#241 [refactor] 단순 이메일 발송 기능 리팩토링
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/mapper/MailCommandMapper.java
Labels: 🔧 refactoring

#249 [fix] 실무테스트 조회 버그 수정
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestListQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestQueryDTO.java
  src/main/resources/mapper/jobtest/JobtestMapper.xml
  src/main/resources/mapper/jobtest/QuestionMapper.xml
Labels: :bug: bug

#252 [refactor] 채용 요청서 등록 로직 수정
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/controller/RecruitmentRequestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/dto/RecruitmentRequestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/service/RecruitmentRequestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/service/RecruitmentRequestCommandServiceImpl.java
Labels: 🔧 refactoring

#245 !hotfix: 스키마 변경 /[feat] 자기소개서 기준표 항목 생성/삭제
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceStandardItemCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceStandardItemCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceStandardItemMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceStandardItemCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceStandardItemCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceStandardItemEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/repository/IntroduceStandardItemRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceTemplateItemQueryDTO.java
  src/main/resources/mapper/introduce/IntroduceStandardItemMapper.xml
  src/main/resources/mapper/introduce/IntroduceStandardMapper.xml
  src/main/resources/mapper/introduce/IntroduceTemplateItemMapper.xml
Labels: :sparkles: enhancement, 🚨 HOTFIX

#250 [refactor] 면접 도메인 DB 수정
  src/main/java/com/piveguyz/empickbackend/employment/interviews/facade/InterviewFacade.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/dto/InterviewCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/mapper/InterviewCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/service/InterviewCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/domain/aggregate/InterviewEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/query/dto/InterviewQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/application/controller/InterviewCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/application/dto/InterviewCriteriaCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/application/mapper/InterviewCriteriaCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/application/service/InterviewCriteriaCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/domain/aggregate/InterviewCriteriaEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/query/controller/InterviewCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/query/dto/InterviewCriteriaQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/query/mapper/InterviewCriteriaMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/query/service/InterviewCriteriaQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/query/service/InterviewCriteriaQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/application/controller/InterviewScoreCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/application/dto/InterviewScoreCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/application/mapper/InterviewScoreCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/application/service/InterviewScoreCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/domain/aggregate/InterviewScoreEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/domain/repository/InterviewScoreRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/query/controller/InterviewScoreQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/query/dto/InterviewScoreQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/command/application/controller/InterviewSheetCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/command/application/service/InterviewSheetCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/query/controller/InterviewSheetQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/application/controller/InterviewSheetItemCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/application/dto/InterviewSheetItemCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/application/mapper/InterviewSheetItemCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/application/service/InterviewSheetItemCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/application/service/InterviewSheetItemCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/domain/aggregate/InterviewSheetItemEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/command/domain/repository/InterviewSheetItemRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/query/controller/InterviewSheetItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/query/dto/InterviewSheetItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/query/mapper/InterviewSheetItemMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/query/service/InterviewSheetItemQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheetItem/query/service/InterviewSheetItemQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/mailTemplate/command/application/controller/MailTemplateCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/mailTemplate/query/controller/MailTemplateQueryController.java
  src/main/resources/mapper/interview/InterviewMapper.xml
  src/main/resources/mapper/interviewCriteria/InterviewCriteriaMapper.xml
  src/main/resources/mapper/interview_score/InterviewScoreMapper.xml
  src/main/resources/mapper/interview_sheet_item/InterviewSheetItemMapper.xml
  src/main/resources/schema/seed/total_insert.sql
  src/main/resources/schema/tables/interview.sql
Labels: 🔧 refactoring, 🚨 HOTFIX

#256 [feat] : 인사 API - 직무, 부서, 직급, 직책
  src/main/java/com/piveguyz/empickbackend/common/enums/IsActive.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/application/controller/DeptCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/application/dto/DeptCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/application/service/DeptCommandService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/application/service/DeptCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/command/domain/aggregate/DepartmentEntity.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/controller/DeptQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/dto/DeptResponseQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/mapper/DeptMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/service/DeptQueryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/department/query/service/DeptQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/command/application/controller/JobCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/command/application/dto/JobCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/command/application/service/JobCommandService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/command/application/service/JobCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/command/domain/aggregate/JobEntity.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/query/controller/JobQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/query/dto/JobResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/query/mapper/JobMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/query/service/JobQueryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/job/query/service/JobQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/command/application/controller/PositionCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/command/application/dto/PositionCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/command/application/service/PositionCommandService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/command/application/service/PositionCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/command/domain/aggregate/PositionEntity.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/command/domain/repository/PositionRepository.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/query/controller/PositionQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/query/dto/PositionQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/query/mapper/PositionMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/query/service/PositionQueryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/position/query/service/PositionQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/command/application/controller/RankCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/command/application/dto/RankCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/command/application/service/RankCommandService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/command/application/service/RankCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/command/domain/aggregate/RankEntity.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/command/domain/repository/RankRepository.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/query/controller/RankQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/query/dto/RankQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/query/mapper/RankMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/query/service/RankQueryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/rank/query/service/RankQueryServiceImpl.java
  src/main/resources/mapper/department/deptMapper.xml
  src/main/resources/mapper/job/JobMapper.xml
  src/main/resources/mapper/position/PositionMapper.xml
  src/main/resources/mapper/rank/RankMapper.xml
  src/main/resources/schema/indexes/common_index.sql
  src/main/resources/schema/indexes/member_index.sql
  src/main/resources/schema/seed/role_insert.sql
  src/main/resources/schema/tables/common.sql
  src/main/resources/schema/tables/role.sql
Labels: :sparkles: enhancement

#260 [refactor] 채용공고 승인 기능 삭제, 게시일 이후 게시중/마감일 이후 종료 상태로 자동 변환 기능 구현
  src/main/java/com/piveguyz/empickbackend/Application.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/scheduler/RecruitmentStatusScheduler.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/enums/RecruitmentStatus.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/domain/repository/RecruitmentRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/dto/RecruitmentQueryDTO.java
Labels: 🔧 refactoring

#263 [feat] 지원서 id로 조회
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicationMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryServiceImp.java
  src/main/resources/mapper/applicant/applicationMapper.xml
Labels: :sparkles: enhancement

#266 [feat] 지원자 id로 조회 / 이름으로 검색 기능 구현(Query)
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicantMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryServiceImp.java
  src/main/resources/mapper/applicant/applicantMapper.xml
Labels: :sparkles: enhancement

#265 [refactor] 채용공고 등록 시 공고 템플릿이 null인 경우 예외 처리
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
Labels: 🔧 refactoring

#274 [feat] 결재 관련 도메인 테이블 생성
  src/main/resources/schema/tables/approval.sql
Labels: :sparkles: enhancement

#269 [feat] : 지원자 id로 지원서 조회 기능 구현(query)
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicationQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicationMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicationQueryServiceImp.java
  src/main/resources/mapper/applicant/applicationMapper.xml
Labels: :sparkles: enhancement

#267 [feat] 실무테스트 입장 검증 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/CreateApplicationJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/JobtestEntryRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateApplicationJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/mapper/ApplicationJobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/aggregate/ApplicationJobtestEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/ApplicationJobtestRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/ApplicationInfoDTO.java
  src/main/java/com/piveguyz/empickbackend/facade/JobtestFacade.java
  src/main/resources/mapper/jobtest/JobtestMapper.xml
Labels: :sparkles: enhancement

#275 [feat] 결재 도메인 Query 기능 구현
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/converter/ApprovalStatusConverter.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/enums/ApprovalStatus.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/dto/ApprovalQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/mapper/ApprovalQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/service/ApprovalQueryService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/service/ApprovalQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/controller/ApprovalCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/dto/ApprovalCategoryQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/mapper/ApprovalCategoryQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/service/ApprovalCategoryQueryService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/service/ApprovalCategoryQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/controller/ApprovalCategoryItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/dto/ApprovalCategoryItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/mapper/ApprovalCategoryItemQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/service/ApprovalCategoryItemQueryService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/service/ApprovalCategoryItemQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/controller/ApprovalContentQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/dto/ApprovalContentQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/mapper/ApprovalContentQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/service/ApprovalContentQueryService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/service/ApprovalContentQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/common/handler/ApprovalStatusTypeHandler.java
  src/main/resources/mapper/approval/ApprovalQueryMapper.xml
  src/main/resources/mapper/approvalCategory/ApprovalCategoryQueryMapper.xml
  src/main/resources/mapper/approvalCategoryItem/ApprovalCategoryItemQueryMapper.xml
  src/main/resources/mapper/approvalContent/ApprovalContentQueryMapper.xml
Labels: :sparkles: enhancement

#279 [feat] 자기소개서 페이지와 연동
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceTemplateCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceTemplateCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceTemplateCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceTemplateQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceTemplateQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceTemplateMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateQueryServiceImp.java
  src/main/resources/mapper/introduce/IntroduceTemplateItemMapper.xml
  src/main/resources/mapper/introduce/IntroduceTemplateMapper.xml
Labels: :sparkles: enhancement

#283 [feat] 지원자 전체 정보 조회
  src/main/java/com/piveguyz/empickbackend/auth/command/application/service/AuthCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantFullInfoDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/mapper/ApplicantMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/service/ApplicantQueryServiceImp.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/dto/MemberRoleQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/mapper/MemberMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryServiceImpl.java
  src/main/resources/mapper/applicant/applicantMapper.xml
  src/main/resources/mapper/introduce/IntroduceStandardMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
Labels: :sparkles: enhancement, 🚨 HOTFIX

#277 [feat] 결재 등록 기능 구현
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/ApprovalCategoryItemDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/ApprovalCommandResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/CreateApprovalCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/service/ApprovalCommandService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/aggregate/ApprovalCategoryEntity.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/aggregate/ApprovalCategoryItemEntity.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/aggregate/ApprovalContentEntity.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/aggregate/ApprovalEntity.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/repository/ApprovalCategoryItemRepository.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/repository/ApprovalContentRepository.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/repository/ApprovalRepository.java
Labels: :sparkles: enhancement

#281 [feat] 채용공고별 지원서 조회 기능 구현
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/controller/RecruitmentQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/mapper/RecruitmentQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/service/RecruitmentQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/service/RecruitmentQueryServiceImpl.java
  src/main/resources/mapper/recruitment/RecruitmentQueryMapper.xml
Labels: :sparkles: enhancement

#284 [feat] 내가 요청받은 결재문서 목록 조회 기능 구현
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/dto/ApprovalReceivedQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/mapper/ApprovalQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/service/ApprovalQueryService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/service/ApprovalQueryServiceImpl.java
  src/main/resources/mapper/approval/ApprovalQueryMapper.xml
Labels: :sparkles: enhancement

#286 [hotfix] 삭제된 공고도 상세조회 가능하도록 쿼리 수정
  src/main/resources/mapper/recruitment/RecruitmentQueryMapper.xml
Labels: 🔧 refactoring, 🚨 HOTFIX

#285 [feat] 요청받은 결재 목록 DTO에 결재차례 추가
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/dto/ApprovalQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/dto/ApprovalReceivedQueryDTO.java
  src/main/resources/schema/tables/approval.sql
Labels: 🔧 refactoring

#288 [feat] 지원자에 쿼리 데이터 추가
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/controller/ApplicantQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantFullInfoDTO.java
  src/main/resources/mapper/applicant/applicantMapper.xml
Labels: :sparkles: enhancement

#282 [feat] 사원 권한 조회 (내권한, 타사원 권한)
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
Labels: :sparkles: enhancement

#287 [feat] 결재 승인/반려 기능 구현
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/ApproveRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/CreateApprovalCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/RejectRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/service/ApprovalCommandService.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/service/ApprovalCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/aggregate/ApprovalEntity.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/domain/enums/ApprovalStatus.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/resources/schema/tables/approval.sql
Labels: :sparkles: enhancement, 🔧 refactoring

#291 [refactor] 기존 사원 검색에 전체 사원 검색 기능 추가
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/mapper/MemberMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/service/MemberQueryServiceImpl.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: 🔧 refactoring

#293 [refactor] 면접 조회(날짜)는 날짜 기준 오름차순 조회로 변경
  src/main/resources/mapper/interview/InterviewMapper.xml
Labels: 🔧 refactoring

#294 [refactor] 실무테스트 문제 수정/삭제 변경
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/domain/repository/AnswerRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/domain/repository/GradingCriteriaRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/JobtestQuestionRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/dto/UpdateQuestionCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/mapper/QuestionOptionMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/service/QuestionCommandServiceImpl.java
Labels: :sparkles: enhancement

#298 [feat] 근태 API : query, command
  src/main/java/com/piveguyz/empickbackend/common/constants/ApiExamples.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/application/controller/AttendanceRecordCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/application/dto/AttendanceRecordCreateRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/application/dto/AttendanceRecordCreateResponseDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/application/dto/AttendanceRecordUpdateRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/application/service/AttendanceRecordCommandService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/application/service/AttendanceRecordCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/domain/aggregate/AttendanceRecordEntity.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/command/domain/repository/AttendanceRecordRepository.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/controller/AttendanceCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/controller/AttendanceRecordQueryController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/dto/AttendanceCategoryQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/dto/AttendanceRecordQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/dto/AttendanceRecordResponseQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/mapper/AttendanceCategoryMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/mapper/AttendanceRecordMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/mapper/AttendanceRecordResponseMapper.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceCategoryService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceCategoryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordResponseService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordResponseServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordService.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordServiceImpl.java
  src/main/resources/mapper/attendance/AttendanceCategoryMapper.xml
  src/main/resources/mapper/attendance/AttendanceRecordMapper.xml
  src/main/resources/mapper/attendance/AttendanceRecordResponseMapper.xml
  src/main/resources/schema/seed/attendance_insert.sql
  src/main/resources/schema/tables/attendance.sql
Labels: :sparkles: enhancement

#255 [feat] 자기소개서 평가 결과 등록/수정/삭제 기능
  src/main/java/com/piveguyz/empickbackend/common/handler/IntroduceResultStatusHandler.java
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceRatingResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceRatingResultCreateCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceRatingResultUpdateCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceResultCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceRatingResultCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceRatingResultCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceRatingResultCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceResultCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceResultCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceRatingResultEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceRatingResultStatus.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceResultEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceResultStatus.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/repository/IntroduceRatingResultRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/repository/IntroduceResultRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceResultQueryDTO.java
Labels: :sparkles: enhancement

#302 !hotfix : 잘 못 설정된 패키지명 수정
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceCategoryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordResponseServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/attendance/query/service/AttendanceRecordServiceImpl.java
Labels: 🚨 HOTFIX

#300 [feat] 면접 점수 등록/수정 시 총점 자동 계산 기능 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/facade/InterviewFacade.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/controller/InterviewCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/service/InterviewCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/service/InterviewCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/domain/repository/InterviewRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/query/service/InterviewQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/application/controller/InterviewScoreCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewer/command/application/controller/InterviewerCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewer/command/application/service/InterviewerCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewer/command/application/service/InterviewerCommandServiceImpl.java
Labels: :sparkles: enhancement, 🔧 refactoring

#301 [feat] 자기소개서 템플릿 항목별 응답 조회/등록 구현
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceTemplateItemResponseCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceTemplateItemResponseCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceTemplateItemResponseCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceTemplateItemResponseCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceTemplateItemResponseCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceTemplateItemResponseEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/repository/IntroduceTemplateItemResponseCommandRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceTemplateItemResponseQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceTemplateItemResponseQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceTemplateItemResponseQueryMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateItemResponseQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceTemplateItemResponseQueryServiceImp.java
  src/main/resources/mapper/introduce/IntroduceTemplateItemResponseMapper.xml
  src/main/resources/schema/tables/introduce.sql
Labels: :sparkles: enhancement

#305 [!HOTFIX] 자기소개서 템플릿 항목별 지원자의 응답 테이블 추가
  src/main/resources/schema/tables/applicant.sql
  src/main/resources/schema/tables/introduce.sql
Labels: 🚨 HOTFIX

#306 [refactor] 점수가 안 입력됐을경우 점수반영 제외 - 면접 점수 최신화 및 자동 계산 기능 구현
  src/main/java/com/piveguyz/empickbackend/employment/interviews/facade/InterviewFacade.java
  src/main/resources/mapper/interviewer/InterviewerMapper.xml
Labels: 🔧 refactoring

#307 [!hotfix] 스키마 변경
  src/main/resources/schema/tables/introduce.sql
Labels: 🚨 HOTFIX

#308 [refactor] 실무테스트 응시 페이지 관련 기능 수정
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/service/AnswerCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/ApplicationJobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/aggregate/ApplicationJobtestEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/ApplicationJobtestRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/JobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestExamQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestExamQuestionSummaryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/mapper/ApplicationJobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/mapper/JobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/ApplicationJobtestQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/ApplicationJobtestQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/JobtestQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/JobtestQueryServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/facade/JobtestFacade.java
  src/main/resources/mapper/jobtest/ApplicationJobtestMapper.xml
  src/main/resources/mapper/jobtest/JobtestMapper.xml
Labels: 🔧 refactoring

#309 [refactor] 프로필 이미지 업로드 방식 변경
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/facade/MemberProfileFacade.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/dto/MemberSignUpRequestDTO.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/service/MemberCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/domain/aggregate/MemberEntity.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/query/controller/MemberQueryController.java
Labels: 🔧 refactoring

#311 [feat] 자기소개서 기준표 id로 상세 조회 기능
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
  src/main/resources/mapper/introduce/IntroduceStandardMapper.xml
Labels: :sparkles: enhancement

#313 [feat] 기준표id로 기준표 항목 전체 조회/ 기준표 항목 수정 기능 구현
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/controller/IntroduceStandardItemCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceStandardItemCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/service/IntroduceStandardItemCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceStandardQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardItemQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceStandardQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceStandardMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceStandardQueryServiceImp.java
  src/main/resources/mapper/introduce/IntroduceStandardItemMapper.xml
  src/main/resources/mapper/introduce/IntroduceStandardMapper.xml
Labels: :sparkles: enhancement

#316 [refactor] api 요청 주소 변경 및 매개변수 추가
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandService.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/service/MailCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/facade/MailFacade.java
  src/main/resources/mapper/mail/MailMapper.xml
Labels: 🔧 refactoring

#319 [refactor] 채용공고 수정 시 템플릿 미지정 허용 및 예외 처리
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/service/RecruitmentCommandServiceImpl.java
Labels: :sparkles: enhancement

#321 [refactor] 실무테스트 수정 관련 DTO 수정
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateJobtestCommandDTO.java
Labels: 🔧 refactoring

#322 [ref] 자소서 dto,xml 수정/ introduce 조회기능 추가 /자소서 평가결과서 dto,mapper,entity 수정/ 지원서 업데이트 로직 리펙토링
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicationCommandServiceImp.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/dto/IntroduceRatingResultCreateCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/application/mapper/IntroduceRatingResultCommandMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/command/domain/aggregate/IntroduceRatingResultEntity.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceResultQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/dto/IntroduceResultQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceQueryServiceImp.java
  src/main/resources/mapper/introduce/introduceMapper.xml
  src/main/resources/mapper/introduce/introduceResultMapper.xml
  src/main/resources/schema/tables/all.sql
Labels: 🔧 refactoring

#323 [refactor] 30분부터 면접 배정 가능 리팩토링
  src/main/resources/mapper/interview/InterviewMapper.xml
Labels: 🔧 refactoring

#326 [refactor] 실무테스트 일정 안내 메일 템플릿 수정
  src/main/resources/templates/jobtest-mail-template.html
Labels: :sparkles: enhancement

#324 [feat] 자기소개서 평가 결과서 id로 조회
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/controller/IntroduceResultQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/mapper/IntroduceResultMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceResultQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/introduce/query/service/IntroduceResultQueryServiceImp.java
  src/main/resources/mapper/introduce/introduceResultMapper.xml
Labels: :sparkles: enhancement

#327 [refactor] 실무테스트 조회 시 문제에 유형 추가
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/JobtestQuestionQueryDTO.java
  src/main/resources/mapper/jobtest/JobtestMapper.xml
Labels: 🔧 refactoring

#325 [ref] 지원서 상태 enum 수정
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/domain/aggregate/ApplicationStatus.java
Labels: 🔧 refactoring

#328 [ref] 프론트 지원서 상태와 연동된 스키마 최신화
  src/main/resources/schema/tables/all.sql
Labels: 🔧 refactoring

#333 [refactor] 지원서 관련 실무테스트 정보 연동
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicantFullInfoDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/query/dto/ApplicationQueryDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/ApplicationJobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/dto/ApplicationJobtestAnswerPageDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/mapper/ApplicationJobtestMapper.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/ApplicationJobtestQueryService.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/service/ApplicationJobtestQueryServiceImpl.java
  src/main/resources/mapper/applicant/applicantMapper.xml
  src/main/resources/mapper/applicant/applicationMapper.xml
  src/main/resources/mapper/jobtest/ApplicationJobtestMapper.xml
Labels: :bug: bug, 🔧 refactoring

#335 [refactor] 실무테스트 수정 구현
  src/main/java/com/piveguyz/empickbackend/common/response/ResponseCode.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/dto/UpdateJobtestCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/service/JobtestCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/ApplicationJobtestRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/JobtestQuestionRepository.java
Labels: :bug: bug, 🔧 refactoring

#336 refactor: 채용공고 게시 상태 변경 주기 1분으로 수정
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/scheduler/RecruitmentStatusScheduler.java
Labels: 🔧 refactoring

#337 [refactor] 사원 비밀번호 데이터 생성을 위한 비밀번호 인코더 구조 수정(반복 동작)
  src/main/java/com/piveguyz/empickbackend/common/util/PasswordEncoder.java
Labels: 🔧 refactoring

#339 [ref] 지원자에 대한 이메일,전화번호 중복처리 삭제
  src/main/java/com/piveguyz/empickbackend/common/config/OpenApiConfig.java
  src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
  src/main/java/com/piveguyz/empickbackend/employment/applicant/command/application/service/ApplicantCommandServiceImp.java
Labels: 🔧 refactoring

#343 [test] 결재 command / 실무테스트 단위테스트 구현
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/dto/CreateApprovalCommandDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/AnswerCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/application/controller/GradingResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/answer/query/controller/AnswerQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/command/application/controller/EvaluationResultCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/evaluation/query/controller/EvaluationResultQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/grading/command/application/controller/GradingCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/ApplicationJobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/application/controller/JobtestQuestionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/domain/repository/JobtestQuestionRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/ApplicationJobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/controller/JobtestQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/command/application/controller/QuestionOptionCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/jobtests/question/query/controller/QuestionQueryController.java
  src/test/java/com/piveguyz/empickbackend/approvals/approval/command/ApprovalCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/answer/command/AnswerCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/answer/query/AnswerQueryTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/ApplicationJobtestCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/JobtestCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/command/JobtestQuestionCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/ApplicationJobtestQueryTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/jobtest/query/JobtestQueryTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/question/command/QuestionCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/question/command/QuestionOptionCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/jobtests/question/query/QuestionQueryTest.java
Labels: :test_tube: test

#344 [test] 면접 및 안내 메일 도메인 테스트 케이스 생성
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/controller/ApprovalCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/controller/ApprovalCategoryItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/controller/ApprovalContentQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/application/controller/InterviewCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/command/domain/repository/InterviewRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interview/query/controller/InterviewQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/application/controller/InterviewCriteriaCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/application/service/InterviewCriteriaCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/command/domain/repository/InterviewCriteriaRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/query/controller/InterviewCriteriaQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/application/controller/InterviewScoreCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/command/domain/repository/InterviewScoreRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/query/controller/InterviewScoreQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/command/application/controller/InterviewSheetCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/command/application/service/InterviewSheetCommandServiceImpl.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/command/domain/repository/InterviewSheetRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/query/controller/InterviewSheetQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewer/command/application/controller/InterviewerCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewer/command/domain/repository/InterviewerRepository.java
  src/main/java/com/piveguyz/empickbackend/employment/interviews/interviewer/query/controller/InterviewerQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/command/application/controller/MailCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/mail/query/controller/MailQueryController.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interview/InterviewCommandControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interview/InterviewQueryControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/InterviewCriteriaCommandControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewCriteria/InterviewCriteriaQueryControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/InterviewScoreCommandControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewScore/InterviewScoreQueryControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/InterviewSheetCommandControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewSheet/InterviewSheetQueryControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewer/InterviewerCommandControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/interviews/interviewer/InterviewerQueryControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/mail/MailCommandControllerTest.java
  src/test/java/com/piveguyz/empickbackend/employment/mail/MailQueryControllerTest.java
  src/test/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandServiceImplTest.java
  src/test/java/com/piveguyz/empickbackend/member/command/domain/repository/MemberRepositoryTest.java
Labels: :test_tube: test

#346 !hotfix : 비회원 지원서 흐름 시큐리티 등록
  src/main/java/com/piveguyz/empickbackend/auth/command/application/controller/AuthCommandController.java
  src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
  src/main/java/com/piveguyz/empickbackend/orgstructure/member/command/application/controller/MemberCommandController.java
Labels: 🚨 HOTFIX

#345 [test] 채용 도메인 테스트 케이스 생성/결재 쿼리 스웨거 태그 정리
  src/main/java/com/piveguyz/empickbackend/approvals/approval/command/application/controller/ApprovalCommandController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalDetailQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalLineQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approval/query/controller/ApprovalQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategory/query/controller/ApprovalCategoryQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalCategoryItem/query/controller/ApprovalCategoryItemQueryController.java
  src/main/java/com/piveguyz/empickbackend/approvals/approvalContent/query/controller/ApprovalContentQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/command/application/controller/RecruitmentCommandController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitment/query/controller/RecruitmentQueryController.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentProcess/command/application/dto/RecruitmentProcessCreateDTO.java
  src/main/java/com/piveguyz/empickbackend/employment/recruitmentRequest/command/application/controller/RecruitmentRequestCommandController.java
  src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentQueryTest.java
  src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentRequestCommandTest.java
  src/test/java/com/piveguyz/empickbackend/employment/recruitment/RecruitmentRequestQueryTest.java
Labels: :test_tube: test

#342 !Hotfix : s3 목록 조회 401 에러 수정
  docs/github-secrets-setup.md
  src/main/java/com/piveguyz/empickbackend/common/config/SecurityConfig.java
  src/test/java/com/piveguyz/empickbackend/member/command/application/service/MemberCommandServiceImplTest.java
  src/test/java/com/piveguyz/empickbackend/member/command/domain/repository/MemberRepositoryTest.java
  src/test/java/com/piveguyz/empickbackend/security/CustomMemberDetailsServiceTest.java
Labels: 🚨 HOTFIX
